const userData = [
    {
        quarter1: {
            quarterName: "I квартал",
            month1: {
                monthName: "Січень",
                days: 31,
                dec: 32,
                ep: 19,
                esv: 18,
                decLabel: "Податкова декларація за 2022 рік",
                decFooter: "Подати до 01.03.2023",
                epLabel: "Сплата ЄП за січень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.01.2023",
                esvLabel: "Сплата ЄСВ за IV квартал 2022 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.01.2023",
            },
            month2: {
                monthName: "Лютий",
                days: 28,
                dec: 29,
                ep: 19,
                //esv: 0,
                decLabel: "Податкова декларація за 2022 рік",
                decFooter: "Подати до 01.03.2023",
                epLabel: "Сплата ЄП за лютий 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.02.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Березень",
                days: 31,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за березень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.03.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter2: {
            quarterName: "II квартал",
            month1: {
                monthName: "Квітень",
                days: 30,
                //dec: 0,
                ep: 19,
                esv: 18,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за квітень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.04.2023",
                esvLabel: "Сплата ЄСВ за І квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.04.2023",
            },
            month2: {
                monthName: "Травень",
                days: 31,
                //dec: 0,
                ep: 18,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за травень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 19.05.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Червень",
                days: 30,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за червнь 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.06.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter3: {
            quarterName: "III квартал",
            month1: {
                monthName: "Липень",
                days: 31,
                //dec: 0,
                ep: 19,
                esv: 18,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за липень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.07.2023",
                esvLabel: "Сплата ЄСВ за ІІ квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.07.2023",
            },
            month2: {
                monthName: "Серпень",
                days: 31,
                //dec: 0,
                ep: 17,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за серпень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 18.08.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Вересень",
                days: 30,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за вересень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.09.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter4: {
            quarterName: "IV квартал",
            month1: {
                monthName: "Жовтень",
                days: 31,
                //dec: 0,
                ep: 19,
                esv: 18,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за жовтень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.10.2023",
                esvLabel: "Сплата ЄСВ за ІІІ квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.10.2023",
            },
            month2: {
                monthName: "Листопад",
                days: 30,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за листопад 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.11.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Грудень",
                days: 31,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за грудень 2023 року",
                epSum: "268,40 грн",
                epFooter: "Сплатити до 20.12.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },
    },

    {
        quarter1: {
            quarterName: "I квартал",
            month1: {
                monthName: "Січень",
                days: 31,
                dec: 32,
                ep: 19,
                esv: 18,
                decLabel: "Податкова декларація за 2022 рік",
                decFooter: "Подати до 01.03.2023",
                epLabel: "Сплата ЄП за січень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.01.2023",
                esvLabel: "Сплата ЄСВ за IV квартал 2022 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.01.2023",
            },
            month2: {
                monthName: "Лютий",
                days: 28,
                dec: 29,
                ep: 19,
                //esv: 0,
                decLabel: "Податкова декларація за 2022 рік",
                decFooter: "Подати до 01.03.2023",
                epLabel: "Сплата ЄП за лютий 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.02.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Березень",
                days: 31,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за березень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.03.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter2: {
            quarterName: "II квартал",
            month1: {
                monthName: "Квітень",
                days: 30,
                //dec: 0,
                ep: 19,
                esv: 18,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за квітень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.04.2023",
                esvLabel: "Сплата ЄСВ за І квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.04.2023",
            },
            month2: {
                monthName: "Травень",
                days: 31,
                //dec: 0,
                ep: 18,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за травень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 19.05.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Червень",
                days: 30,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за червень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.06.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter3: {
            quarterName: "III квартал",
            month1: {
                monthName: "Липень",
                days: 31,
                //dec: 0,
                ep: 19,
                esv: 18,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за липень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.07.2023",
                esvLabel: "Сплата ЄСВ за ІІ квартал 2023",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.07.2023",
            },
            month2: {
                monthName: "Серпень",
                days: 31,
                //dec: 0,
                ep: 17,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за серпень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 18.08.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Вересень",
                days: 30,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за вересень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.09.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter4: {
            quarterName: "IV квартал",
            month1: {
                monthName: "Жовтень",
                days: 31,
                //dec: 0,
                ep: 19,
                esv: 18,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за жовтень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.10.2023",
                esvLabel: "Сплата ЄСВ за ІІІ квартал 2023",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.10.2023",
            },
            month2: {
                monthName: "Листопад",
                days: 30,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за листопад 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.11.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Грудень",
                days: 31,
                //dec: 0,
                ep: 19,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "Сплата ЄП за грудень 2023 року",
                epSum: "1340 грн",
                epFooter: "Сплатити до 20.12.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },
    },

    {
        quarter1: {
            quarterName: "I квартал",
            month1: {
                monthName: "Січень",
                days: 31,
                dec: 19,
                ep: 29,
                esv: 18,
                decLabel: "Податкова декларація за грудень 2022 року",
                decFooter: "Подати до 20.01.2023",
                epLabel: "Сплата ЄП за грудень 2022 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 30.01.2023",
                esvLabel: "Сплата ЄСВ за IV квартал 2022 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.01.2023",
            },
            month2: {
                monthName: "Лютий",
                days: 28,
                dec: 19,
                ep: 30,
                //esv: 0,
                decLabel: "Податкова декларація за січень 2023 року",
                decFooter: "Подати до 20.02.2023",
                epLabel: "Сплата ЄП за січень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 02.03.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Березень",
                days: 31,
                dec: 19,
                ep: 29,
                //esv: 0,
                decLabel: "Податкова декларація за лютий 2023 року",
                decFooter: "Подати до 20.03.2023",
                epLabel: "Сплата ЄП за лютий 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 30.03.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter2: {
            quarterName: "II квартал",
            month1: {
                monthName: "Квітень",
                days: 30,
                dec: 19,
                ep: 27,
                esv: 18,
                decLabel: "Податкова декларація за березень 2023 року",
                decFooter: "Подати до 20.04.2023",
                epLabel: "Сплата ЄП за березень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 28.04.2023",
                esvLabel: "Сплата ЄСВ за І квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.04.2023",
            },
            month2: {
                monthName: "Травень",
                days: 31,
                dec: 19,
                ep: 32,
                //esv: 0,
                decLabel: "Податкова декларація за квітень 2023 року",
                decFooter: "Подати до 20.05.2023",
                epLabel: "Сплата ЄП за квітень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 01.06.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Червень",
                days: 30,
                dec: 19,
                ep: 29,
                //esv: 0,
                decLabel: "Податкова декларація за травень 2023 року",
                decFooter: "Подати до 20.06.2023",
                epLabel: "Сплата ЄП за травень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 30.06.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter3: {
            quarterName: "III квартал",
            month1: {
                monthName: "Липень",
                days: 31,
                dec: 19,
                ep: 27,
                esv: 18,
                decLabel: "Податкова декларація за червень 2023 року",
                decFooter: "Подати до 20.07.2023",
                epLabel: "Сплата ЄП за червень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 28.07.2023",
                esvLabel: "Сплата ЄСВ за ІІ квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.07.2023",
            },
            month2: {
                monthName: "Серпень",
                days: 31,
                dec: 20,
                ep: 30,
                //esv: 0,
                decLabel: "Податкова декларація за липень 2023 року",
                decFooter: "Подати до 21.08.2023",
                epLabel: "Сплата ЄП за липень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 31.08.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Вересень",
                days: 30,
                dec: 19,
                ep: 28,
                //esv: null,
                decLabel: "Податкова декларація за серпень 2023 року",
                decFooter: "Подати до 20.09.2023",
                epLabel: "Сплата ЄП за серпень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 29.09.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter4: {
            quarterName: "IV квартал",
            month1: {
                monthName: "Жовтень",
                days: 31,
                dec: 19,
                ep: 29,
                esv: 18,
                decLabel: "Податкова декларація за вересень 2023 року",
                decFooter: "Подати до 20.10.2023",
                epLabel: "Сплата ЄП за вересень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 30.10.2023",
                esvLabel: "Сплата ЄСВ за ІІІ квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.10.2023",
            },
            month2: {
                monthName: "Листопад",
                days: 30,
                dec: 19,
                ep: 29,
                //esv: null,
                decLabel: "Податкова декларація за жовтень 2023 року",
                decFooter: "Подати до 20.11.2023",
                epLabel: "Сплата ЄП за жовтень 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 30.11.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Грудень",
                days: 31,
                dec: 19,
                ep: 28,
                //esv: 0,
                decLabel: "Податкова декларація за листопад 2023 року",
                decFooter: "Подати до 20.12.2023",
                epLabel: "Сплата ЄП за листопад 2023 року",
                epSum: "2% від доходу",
                epFooter: "Сплатити до 29.12.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },
    },

    {
        quarter1: {
            quarterName: "I квартал",
            month1: {
                monthName: "Січень",
                days: 31,
                dec: 32,
                ep: 32,
                esv: 18,
                decLabel: "Податкова декларація за 2022 рік",
                decFooter: "Подати до 09.02.2023",
                epLabel: "Сплата ЄП за IV квартал 2022 року",
                epSum: "5% від доходу",
                epFooter: "Сплатити до 21.02.2023",
                esvLabel: "Сплата ЄСВ за IV квартал 2022 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.01.2023",
            },
            month2: {
                monthName: "Лютий",
                days: 28,
                dec: 8,
                ep: 20,
                //esv: 0,
                decLabel: "Податкова декларація за 2022 рік",
                decFooter: "Подати до 09.02.2023",
                epLabel: "Сплата ЄП за IV квартал 2022 року",
                epSum: "5% від доходу",
                epFooter: "Сплатити до 21.02.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Березень",
                days: 31,
                //dec: 0,
                //ep: 0,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "",
                epSum: "",
                epFooter: "",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter2: {
            quarterName: "II квартал",
            month1: {
                monthName: "Квітень",
                days: 30,
                dec: 31,
                ep: 31,
                esv: 18,
                decLabel: "Податкова декларація за І квартал 2023 року",
                decFooter: "Подати до 10.05.2023",
                epLabel: "Сплата ЄП за І квартал 2023 року",
                epSum: "5% від доходу",
                epFooter: "Сплатити до 19.05.2023",
                esvLabel: "Сплата ЄСВ за І квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.04.2023",
            },
            month2: {
                monthName: "Травень",
                days: 31,
                dec: 9,
                ep: 18,
                //esv: 0,
                decLabel: "Податкова декларація за І квартал 2023 року",
                decFooter: "Подати до 10.05.2023",
                epLabel: "Сплата ЄП за І квартал 2023 року",
                epSum: "5% від доходу",
                epFooter: "Сплатити до 19.05.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Червень",
                days: 30,
                //dec: 0,
                //ep: 0,
                //esv: 0,
                decLabel: "",
                decFooter: "",
                epLabel: "",
                epSum: "",
                epFooter: "",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter3: {
            quarterName: "III квартал",
            month1: {
                monthName: "Липень",
                days: 31,
                dec: 32,
                ep: 32,
                esv: 18,
                decLabel: "Податкова декларація за ІІ квартал 2023 року",
                decFooter: "Подати до 09.08.2023",
                epLabel: "Сплата ЄСВ за ІІ квартал 2023 року",
                epSum: "5% від доходу",
                epFooter: "Сплатити до 18.08.2023",
                esvLabel: "Сплата ЄСВ за ІІ квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.07.2023",
            },
            month2: {
                monthName: "Серпень",
                days: 31,
                dec: 8,
                ep: 17,
                //esv: 0,
                decLabel: "Податкова декларація за ІІ квартал 2023 року",
                decFooter: "Подати до 09.08.2023",
                epLabel: "Сплата ЄСВ за ІІ квартал 2023 року",
                epSum: "5% від доходу",
                epFooter: "Сплатити до 18.08.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Вересень",
                days: 30,
                //dec: null,
                //ep: null,
                //esv: null,
                decLabel: "",
                decFooter: "",
                epLabel: "",
                epSum: "",
                epFooter: "",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },

        quarter4: {
            quarterName: "IV квартал",
            month1: {
                monthName: "Жовтень",
                days: 31,
                dec: 32,
                ep: 32,
                esv: 18,
                decLabel: "Податкова декларація за ІІІ квартал 2023 року",
                decFooter: "Подати до 09.11.2023",
                epLabel: "Сплата ЄП за ІІІ квартал 2023 року",
                epSum: "5% від доходу",
                epFooter: "Сплатити до 17.10.2023",
                esvLabel: "Сплата ЄСВ за ІІІ квартал 2023 року",
                esvSum: "4422 грн",
                esvFooter: "Сплатити до 19.10.2023",
            },
            month2: {
                monthName: "Листопад",
                days: 30,
                dec: 8,
                ep: 16,
                //esv: null,
                decLabel: "Податкова декларація за ІІІ квартал 2023 року",
                decFooter: "Подати до 09.11.2023",
                epLabel: "Сплата ЄП за ІІІ квартал 2023 року",
                epSum: "5% від доходу",
                epFooter: "Сплатити до 17.10.2023",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            },
            month3: {
                monthName: "Грудень",
                days: 31,
                //dec: null,
                //ep: null,
                //esv: null,
                decLabel: "",
                decFooter: "",
                epLabel: "",
                epSum: "",
                epFooter: "",
                esvLabel: "",
                esvSum: "",
                esvFooter: "",
            }
        },
    }
]

export default userData;